import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st


df = pd.read_excel('data/Colombianos_registrados_en_el_exterior_20251113 (1).xlsx', engine='openpyxl')

# Diccionarios de reemplazo
remplasos_area = {
    'ECONOM�A': 'ECONOMIA',
    'ADMINISTRACI�N': 'ADMINISTRACION',
    'INGENIER�A': 'INGENIERIA',
    'AGRONOM�A': 'AGRONOMIA',
    'CIENCIAS DE LA EDUCACI�N': 'CIENCIAS DE LA EDUCACION',
    'CIENCIAS SOCIALES, PERIODISMO E INFORMACI�N': 'CIENCIAS SOCIALES, PERIODISMO E INFORMACION',
    'MATEM�TICAS': 'MATEMATICAS',
    'TECNOLOG�AS': 'TECNOLOGIAS',
    'PROGRAMAS Y CERTIFICACIONES GEN�RICAS': 'PROGRAMAS Y CERTIFICACIONES GENERICAS',
    'ESTAD�STICA': 'ESTADISTICA',
    'AVIACI�N': 'AVIACION',
    'EDUCACI�N': 'EDUCACION',
    'DISE�O': 'DISENO',
    'F�SICA': 'FISICA',
    'M�SICA': 'MUSICA',
    'NUTRICI�N': 'NUTRICION',
    'ANTROPOLOG�A': 'ANTROPOLOGIA',
    'LING��STICA': 'LINGUISTICA',
    'QU�MICA': 'QUIMICA',
    'ODONTOLOG�A': 'ODONTOLOGIA',
    'GEOLOG�A': 'GEOLOGIA',
    'FILOSOF�A': 'FILOSOFIA',
    'INSTRUMENTACI�N': 'INSTRUMENTACION',
    'SALUD P�BLICA': 'SALUD PUBLICA',
    'OPTOMETR�A': 'OPTOMETRIA',
    'TECNOLOGIAS DE LA INFORMACI�N Y LA COMUNICACI�N (TIC)':
    'TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION (TIC)',
    'INGENIERIA, INDUSTRIA Y CONSTRUCCI�N': 'INGENIERIA, INDUSTRIA Y CONSTRUCCION'    
}

# Diccionario con todos los reemplazos para 'Sub Area Conocimiento'
remplazos_subarea = {
    'PERIODISMO, COMUNICACI�N SOCIAL Y AFINES': 'PERIODISMO, COMUNICACION SOCIAL Y AFINES',
    'ADMINISTRACI�N': 'ADMINISTRACION',
    'INGENIER�A INDUSTRIAL Y AFINES': 'INGENIERIA INDUSTRIAL Y AFINES',
    'SOCIOLOG�A, TRABAJO SOCIAL Y AFINES': 'SOCIOLOGIA, TRABAJO SOCIAL Y AFINES',
    'CONTADUR�A P�BLICA': 'CONTADURIA PUBLICA',
    'ENFERMER�A': 'ENFERMERIA',
    'INGENIER�A CIVIL Y AFINES': 'INGENIERIA CIVIL Y AFINES',
    'AGRONOM�A': 'AGRONOMIA',
    'INGENIER�A MEC�NICA Y AFINES': 'INGENIERIA MECANICA Y AFINES',
    'PSICOLOG�A Y AFINES': 'PSICOLOGIA Y AFINES',
    'ECONOM�A': 'ECONOMIA',
    'DISE�O': 'DISENO',
    'INGENIER�A EL�CTRICA Y AFINES': 'INGENIERIA ELECTRICA Y AFINES',
    'INGENIER�A ELECTR�NICA, TELECOMUNICACIONES Y AFINES': 'INGENIERIA ELECTRONICA, TELECOMUNICACIONES Y AFINES',
    'INGENIER�A EN SISTEMAS, TELEM�TICA Y AFINES': 'INGENIERIA EN SISTEMAS, TELEMATICA Y AFINES',
    'CIENCIA POL�TICA Y/O RELACIONES INTERNACIONALES': 'CIENCIA POLITICA Y/O RELACIONES INTERNACIONALES',
    'EDUCACI�N': 'EDUCACION',
    'FILOSOF�A, TEOLOG�A Y AFINES': 'FILOSOFIA, TEOLOGIA Y AFINES',
    'GEOLOG�A': 'GEOLOGIA',
    'ODONTOLOG�A': 'ODONTOLOGIA',
    'INGENIER�A QU�MICA Y AFINES': 'INGENIERIA QUIMICA Y AFINES',
    'ARTES DRAM�TICAS Y REPRESENTATIVAS': 'ARTES DRAMATICAS Y REPRESENTATIVAS',
    'BACTERIOLOG�A': 'BACTERIOLOGIA',
    'SALUD P�BLICA': 'SALUD PUBLICA',
    'MATEM�TICAS, ESTAD�STICA Y AFINES': 'MATEMATICAS, ESTADISTICA Y AFINES',
    'ARTES PL�STICAS, VISUALES Y AFINES': 'ARTES PLASTICAS, VISUALES Y AFINES',
    'INSTRUMENTACI�N QUIR�RGICA': 'INSTRUMENTACION QUIRURGICA',
    'BIOLOG�A, MICROBIOLOG�A Y AFINES': 'BIOLOGIA, MICROBIOLOGIA Y AFINES',
    'INGENIER�A DE MINAS, METALURGIA Y AFINES': 'INGENIERIA DE MINAS, METALURGIA Y AFINES',
    'INGENIER�A ADMINISTRATIVA Y AFINES': 'INGENIERIA ADMINISTRATIVA Y AFINES',
    'INGENIER�A AGR�COLA, FORESTAL Y AFINES': 'INGENIERIA AGRICOLA, FORESTAL Y AFINES',
    'DEPORTES, EDUCACI�N F�SICA Y RECREACI�N': 'DEPORTES, EDUCACION FISICA Y RECREACION',
    'INGENIER�A AMBIENTAL, SANITARIA Y AFINES': 'INGENIERIA AMBIENTAL, SANITARIA Y AFINES',
    'NUTRICI�N Y DIET�TICA': 'NUTRICION Y DIETETICA',
    'ANTROPOLOG�A O ARTES LIBERALES': 'ANTROPOLOGIA O ARTES LIBERALES',
    'LENGUAS MODERNAS, FILOLOG�A, LING��STICA Y AFINES': 'LENGUAS MODERNAS, FILOLOGIA, LINGUISTICA Y AFINES',
    'INGENIER�A AGROINDUSTRIAL, ALIMENTOS Y AFINES': 'INGENIERIA AGROINDUSTRIAL, ALIMENTOS Y AFINES',
    'M�SICA': 'MUSICA',
    'INGENIER�A BIOM�DICA Y AFINES': 'INGENIERIA BIOMEDICA Y AFINES',
    'QU�MICA Y AFINES': 'QUIMICA Y AFINES',
    'INGENIER�A DE PETR�LEOS': 'INGENIERIA DE PETROLEOS',
    'F�SICA': 'FISICA',
    'OPTOMETR�A': 'OPTOMETRIA',
    'INGENIER�A AGRON�MICA, PECUARIA Y AFINES': 'INGENIERIA AGRONOMICA, PECUARIA Y AFINES',
    'OTRAS INGENIER�AS': 'OTRAS INGENIERIAS',
    'FORMACI�N MILITAR': 'FORMACION MILITAR',
    'BIBLIOTECOLOG�A': 'BIBLIOTECOLOGIA',
    'TECNOLOG�AS DE LA INFORMACI�N Y LA COMUNICACI�N (TIC)': 'TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION (TIC)',
    'GEOGRAF�A O HISTORIA': 'GEOGRAFIA O HISTORIA',
    'EDUCACION FISICA Y RECREACI�N': 'EDUCACION FISICA Y RECREACION',
    'AVIACI�N': 'AVIACION'
}

remplasos_nivel = {
    'NO INDICA': 'NO INDICA',
    'PREGRADO - PROFESIONAL': 'PREGRADO PROFESIONAL',
    'PREGRADO PROFESIONAL': 'PREGRADO PROFESIONAL',
    'BACHILLERATO': 'BACHILLERATO',
    'POSTGRADO - ESPECIALIZACION': 'POSTGRADO ESPECIALIZACION',
    'POSTGRADO - ESPECIALIZACI�N': 'POSTGRADO ESPECIALIZACION',
    'PRIMARIA': 'PRIMARIA',
    'POSTGRADO - MAESTRIA': 'POSTGRADO MAESTRIA',
    'PREGRADO - TECNICO PROFESIONAL': 'PREGRADO TECNICO PROFESIONAL',
    'PREGRADO - T�CNICO PROFESIONAL': 'PREGRADO TECNICO PROFESIONAL',
    'POSTGRADO - DOCTORADO': 'POSTGRADO DOCTORADO',
    'NINGUNO': 'NINGUNO',
    'PREGRADO - TECNOLOGICO': 'PREGRADO TECNOLOGICO',
    'PREGRADO - TECNOL�GICO': 'PREGRADO TECNOLOGICO',
    '(NO REGISTRA)': 'NO REGISTRA',
    'NO REGISTRA': 'NO REGISTRA',
    'SIN PROFESION': 'SIN PROFESION',
    'SIN PROFESI�N': 'SIN PROFESION',
    'UNIVERSITARIO': 'PREGRADO PROFESIONAL',
    'TECNICA PROFESIONAL': 'PREGRADO TECNICO PROFESIONAL',
    'T�CNICA PROFESIONAL': 'PREGRADO TECNICO PROFESIONAL',
    'ESPECIALIZACION': 'POSTGRADO ESPECIALIZACION',
    'ESPECIALIZACI�N': 'POSTGRADO ESPECIALIZACION',
    'MAESTRIA': 'POSTGRADO MAESTRIA',
    'DOCTORADO': 'POSTGRADO DOCTORADO',
    'TECNOLÓGICA': 'PREGRADO TECNOLOGICO',
    'TECNOL�GICA': 'PREGRADO TECNOLOGICO',
    'POSTGRADO POSTGRADO POSTGRADO POSTGRADO ESPECIALIZACION': 'POSTGRADO ESPECIALIZACION',
    'POSTGRADO POSTGRADO POSTGRADO POSTGRADO POSTGRADO MAESTRIA': 'POSTGRADO MAESTRIA',
    'POSTGRADO POSTGRADO POSTGRADO POSTGRADO POSTGRADO DOCTORADO': 'POSTGRADO DOCTORADO',
    'POSTGRADO POSTGRADO POSTGRADO POSTGRADO MAESTRIA': 'POSTGRADO MAESTRIA',
    'POSTGRADO POSTGRADO POSTGRADO POSTGRADO DOCTORADO': 'POSTGRADO DOCTORADO',
    '(NO REGISTRA)':'NINGUNO',
    'SIN PROFESION':'NINGUNO',
    'NO INDICA':'NINGUNO',
    '(NINGUNO)':'NINGUNO'
}

df['Nivel Académico'] = df['Nivel Académico'].replace(remplasos_nivel, regex=True)
df['Área Conocimiento'] = df['Área Conocimiento'].replace(remplasos_area, regex=True)
df['Sub Area Conocimiento'] = df['Sub Area Conocimiento'].replace(remplazos_subarea, regex=True)
df['Nivel Académico'] = df['Nivel Académico'].replace({'POSTGRADO POSTGRADO DOCTORADO': 'POSTGRADO DOCTORADO',
 'POSTGRADO POSTGRADO MAESTRIA': 'POSTGRADO MAESTRIA'}, regex=True)


df.loc[df['Nivel Académico'] == '(NINGUNO)', 'Nivel Académico'] = 'NINGUNO'
df.loc[df['Área Conocimiento'] == 'TECNOLOGIAS DE LA INFORMACI�N Y LA COMUNICACI�N (TIC)', 'Área Conocimiento'] = 'TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION (TIC)'
df.loc[df['Sub Area Conocimiento'] == 'TECNOLOG�AS DE LA INFORMACI�N Y LA COMUNICACI�N (TIC)', 'Sub Area Conocimiento'] = 'TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION (TIC)'

df[['pais de origen', 'departamento de origen', 'Ciudad de Nacimiento']] = df['Ciudad de Nacimiento'].str.split('/', expand=True)

df = df[df['pais de origen'] == 'COLOMBIA']

df[['Ciudad de residencia', 'Estado de residencia']] = df['Ciudad de Residencia'].str.split('/', expand=True)
df[['Año de Registro', 'Hora de Registro']] = df['Fecha de Registro'].str.split('-', expand=True)

df[['Ciudad de residencia', 'Estado de residencia']] = df['Ciudad de Residencia'].str.split('/', expand=True)
df[['Año de Registro', 'Hora de Registro']] = df['Fecha de Registro'].str.split('-', expand=True)

condicion1 = df['Área Conocimiento'].isin(['NINGUNA', 'NO INDICA', '(NO REGISTRA)'])
condicion2= df['Sub Area Conocimiento'].isin(['NINGUNA', 'NO INDICA', '(NO REGISTRA)'])
df.loc[condicion1, 'Área Conocimiento'] = 'NINGUNA'
df.loc[condicion2, 'Sub Area Conocimiento'] = 'NINGUNA'

cond = (
    (df['Área Conocimiento'] != 'NINGUNA') &
    (df['Nivel Académico'].isin(['NO INDICA', 'NINGUNO']))
)

df = df[~cond]

df = df[df['Año de Registro'] != '1900']

df['Etnia de la persona'] = df['Etnia de la persona'].replace('IND�GENA', 'INDIGENA')

st.set_page_config(
    page_title='Reguistros de Migrantes Colombianos en el Exterior',
    layout='centered',
    initial_sidebar_state='collapsed'
    )
st.markdown(
    '''
    <style>
        .block-container {
        max-width: 1200px;
        }

    ''',
    unsafe_allow_html=True
)


